ci-image:
  stage: build
  image: docker:20.10-dind
  services:
      - name: docker:20.10-dind
  variables:
      DOCKER_DRIVER: overlay2
  script:
    - 'docker build -t $CI_REGISTRY/linaro/tuxrun/ci:$CI_COMMIT_REF_SLUG -f Dockerfile.ci .'
    - 'docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY'
    - 'docker push $CI_REGISTRY/linaro/tuxrun/ci:$CI_COMMIT_REF_SLUG'
  rules:
    - changes:
      - Dockerfile.ci

.test:
  image: $CI_REGISTRY/linaro/tuxrun/ci:$CI_COMMIT_REF_SLUG
  script:
    - make $CI_JOB_NAME

unit-tests:
  extends: .test

stylecheck:
  extends: .test

typecheck:
  extends: .test

spellcheck:
  extends: .test
